export const COLORS = {
  primary: '#0068AF',
  white: '#FFFFFF',
  gray: '#ECF0F4',
  n1: '#ffffff',
  n2: '#C5C6C8',
  n3: '#a8a9ad',
  n4: '#868a8d',
  n5: '#555659',
  n6: '#000000',
  gradient1: '#00adef',
  gradient2: '#eff0f2',
  gradient3: '#0073c6',
  gradient4: '#e2edf3',
  secondary1: '#19b2eb',
  secondary2: '#5d9cf9',
  secondary3: '#1084f4',
  secondary4: '#f60000',
  secondary5: '#1E487E',
};

export const images = {
  iconTick:require("../img/icon_tick.png"),
  tick:require("../img/tick.png"),
  english:require("../img/flag_english.png"),
  japan:require("../img/flag_japan.png"),
  korean:require("../img/flag_korea.png"),
  china:require("../img/flag_china.png"),
  anhthe: require('../img/anhthe.png'),
  unlock_2: require('../img/ic_unlock_2.png'),
  checkActive: require('../img/ic_check_active.png'),
  checkInActive: require('../img/ic_check_inactive.png'),
  faceId: require('../img/face_id.png'),
  bginfo: require('../img/bg_info.png'),
  avatar: require('../img/avatar.png'),
  background: require('../img/background.png'),
  search_world: require('../img/search_world.png'),
  vneid: require('../img/vneid.png'),
  logo: require('../img/ic_logo.png'),
  address: require('../img/address.png'),
  arrow_next: require('../img/arrow_next.png'),
  back_1: require('../img/back_1.png'),
  back: require('../img/back.png'),
  bhnt: require('../img/bhnt.png'),
  bhntld: require('../img/bhntld.png'),
  bhxh: require('../img/bhxh.png'),
  bhyt: require('../img/bhyt.png'),
  computer: require('../img/computer.png'),
  copyright: require('../img/copyright.png'),
  dichvucong: require('../img/dichvucong.png'),
  eye_1: require('../img/eye_1.png'),
  eye: require('../img/eye.png'),
  file: require('../img/file.png'),
  fingerprint: require('../img/fingerprint.png'),
  flag: require('../img/flag.png'),
  ic: require('../img/ic.png'),
  info: require('../img/info.png'),
  lock: require('../img/lock.png'),
  menu: require('../img/menu.png'),
  news: require('../img/news.png'),
  next: require('../img/next.png'),
  noti_1: require('../img/noti_1.png'),
  noti: require('../img/noti.png'),
  password: require('../img/password.png'),
  pencil: require('../img/pencil.png'),
  power: require('../img/power.png'),
  qlcn: require('../img/qlcanhan.png'),
  qr_code: require('../img/qr_code.png'),
  quatrinhthamgia: require('../img/quatrinhthamgia.png'),
  search: require('../img/search.png'),
  setting: require('../img/setting.png'),
  sokhamchuabenh: require('../img/sokhamchuabenh.png'),
  support: require('../img/support.png'),
  support_1: require('../img/support_1.png'),
  user: require('../img/user.png'),
  view_up: require('../img/view_up.png'),
};
